"""
LoRA-fine-tuned model agent for credit risk analysis.

Provides the same interface as BaselineAgent but uses a Mistral-7B model
with LoRA adapters loaded from a saved checkpoint.

Exports:
    LoRAAgent
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any, Dict, List, Optional

import pandas as pd

logger = logging.getLogger(__name__)


class LoRAAgent:
    """Credit risk analysis agent using a LoRA fine-tuned Mistral-7B model.

    Args:
        model: A HuggingFace CausalLM model with LoRA adapters already loaded.
        tokenizer: Corresponding tokenizer.
    """

    def __init__(self, model: Any, tokenizer: Any) -> None:
        self.model = model
        self.tokenizer = tokenizer
        logger.info("LoRAAgent initialized.")

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate(self, prompt: str, max_new_tokens: int = 512) -> str:
        """Run inference and return the generated text (excluding prompt).

        Args:
            prompt: Full instruction prompt string.
            max_new_tokens: Maximum number of tokens to generate.

        Returns:
            Generated text string.
        """
        import torch  # type: ignore

        try:
            from transformers import pipeline  # type: ignore
        except ImportError as exc:  # pragma: no cover
            raise ImportError("Install transformers: pip install transformers") from exc

        inputs = self.tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=3072,
        )
        device = next(self.model.parameters()).device
        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                do_sample=False,
                temperature=1.0,
                pad_token_id=self.tokenizer.eos_token_id,
            )

        input_length = inputs["input_ids"].shape[1]
        generated_tokens = outputs[0][input_length:]
        return self.tokenizer.decode(generated_tokens, skip_special_tokens=True)

    def _parse_output(self, raw_output: str, ticker: str) -> dict:
        """Parse JSON from model output, falling back to defaults on error.

        Args:
            raw_output: Raw text generated by the model.
            ticker: Company ticker (used for fallback values).

        Returns:
            Parsed prediction dictionary.
        """
        try:
            start = raw_output.find("{")
            end = raw_output.rfind("}") + 1
            if start != -1 and end > start:
                data = json.loads(raw_output[start:end])
                return data
        except json.JSONDecodeError:
            logger.warning("Could not parse JSON from LoRA output for %s.", ticker)

        return {
            "predicted_score": 50.0,
            "risk_level": "medium",
            "key_signals": [],
            "citations": [],
        }

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def analyze(
        self,
        ticker: str,
        company_name: str,
        sections: Dict[str, str],
    ) -> dict:
        """Analyze a single company's 10-K sections for credit risk.

        Args:
            ticker: Stock ticker symbol.
            company_name: Full company name.
            sections: Dict with keys item_1a, item_7, item_8, full_text.

        Returns:
            Prediction dictionary with keys:
                ticker, company_name, predicted_score (float 0–100),
                predicted_label (int 0/1), risk_level (str),
                key_signals (list), citations (list), raw_output (str),
                approach (str).
        """
        from src.prompts.lora_prompt import build_lora_prompt

        item_1a = sections.get("item_1a", "")[:4000]
        item_7 = sections.get("item_7", "")[:4000]

        prompt = build_lora_prompt(
            company_name=company_name,
            ticker=ticker,
            item_1a=item_1a,
            item_7=item_7,
        )

        logger.info("Running LoRA inference for %s (%s)...", company_name, ticker)
        try:
            raw_output = self._generate(prompt)
        except Exception as exc:  # noqa: BLE001
            logger.error("LoRA generation failed for %s: %s", ticker, exc)
            raw_output = ""

        parsed = self._parse_output(raw_output, ticker)

        predicted_score = float(parsed.get("predicted_score", 50.0))
        predicted_score = max(0.0, min(100.0, predicted_score))
        predicted_label = 1 if predicted_score >= 70.0 else 0
        risk_level = parsed.get("risk_level", "medium")

        return {
            "ticker": ticker,
            "company_name": company_name,
            "predicted_score": round(predicted_score, 2),
            "predicted_label": predicted_label,
            "risk_level": risk_level,
            "key_signals": json.dumps(parsed.get("key_signals", [])),
            "citations": json.dumps(parsed.get("citations", [])),
            "raw_output": raw_output,
            "approach": "lora",
        }

    def analyze_all(
        self,
        companies_df: pd.DataFrame,
        sections_dir: str,
    ) -> pd.DataFrame:
        """Analyze all companies and return a predictions DataFrame.

        Args:
            companies_df: DataFrame with columns ticker and company_name
                (or name).
            sections_dir: Directory containing ``{ticker}_sections.json`` files.

        Returns:
            Predictions DataFrame with the standard schema, saved to
            ``data/results/lora_predictions.csv``.
        """
        records: List[dict] = []

        for _, row in companies_df.iterrows():
            ticker = row.get("ticker", "")
            company_name = row.get("company_name", row.get("name", ticker))

            sections_path = os.path.join(sections_dir, f"{ticker}_sections.json")
            if not os.path.exists(sections_path):
                logger.warning("Sections not found for %s at %s", ticker, sections_path)
                continue

            try:
                with open(sections_path, "r", encoding="utf-8") as fh:
                    sections = json.load(fh)
            except Exception as exc:  # noqa: BLE001
                logger.error("Failed to load sections for %s: %s", ticker, exc)
                continue

            result = self.analyze(ticker, company_name, sections)
            records.append(result)
            logger.info("Completed analysis for %s: score=%.1f", ticker, result["predicted_score"])

        df = pd.DataFrame(records)
        logger.info("LoRA analysis complete: %d companies processed.", len(df))
        return df

    # ------------------------------------------------------------------
    # Factory class method
    # ------------------------------------------------------------------

    @classmethod
    def from_adapter_path(cls, adapter_path: str, base_model_name: Optional[str] = None) -> "LoRAAgent":
        """Load a LoRA-adapted model from a saved adapter directory.

        Args:
            adapter_path: Path to the saved LoRA adapter (output of
                lora_trainer.train()).
            base_model_name: Optional base model name override. If not
                provided, reads from adapter config.

        Returns:
            Instantiated LoRAAgent.
        """
        try:
            from peft import PeftModel  # type: ignore
            from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig  # type: ignore
        except ImportError as exc:
            raise ImportError(
                "Install peft and transformers: pip install peft transformers bitsandbytes"
            ) from exc

        import torch

        # Determine base model name
        if base_model_name is None:
            adapter_config_path = os.path.join(adapter_path, "adapter_config.json")
            if os.path.exists(adapter_config_path):
                with open(adapter_config_path, "r") as fh:
                    adapter_config = json.load(fh)
                base_model_name = adapter_config.get("base_model_name_or_path", "mistralai/Mistral-7B-Instruct-v0.2")
            else:
                base_model_name = "mistralai/Mistral-7B-Instruct-v0.2"

        logger.info("Loading base model '%s' for LoRA inference...", base_model_name)

        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
        )
        base_model = AutoModelForCausalLM.from_pretrained(
            base_model_name,
            quantization_config=bnb_config,
            device_map="auto",
            trust_remote_code=True,
        )
        model = PeftModel.from_pretrained(base_model, adapter_path)
        model.eval()

        tokenizer = AutoTokenizer.from_pretrained(adapter_path, trust_remote_code=True)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

        logger.info("LoRA adapter loaded from %s", adapter_path)
        return cls(model=model, tokenizer=tokenizer)
